name: CI/CD for React App

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: check path
        run : pwd

      - name: Set working directory
        run:  cd /home/runner/work/Loan_Emi_Calculator/Loan_Emi_Calculator/frontend_loan_calendar && ls

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run:  cd /home/runner/work/Loan_Emi_Calculator/Loan_Emi_Calculator/frontend_loan_calendar && npm install

      - name: Build Project
        run:  cd /home/runner/work/Loan_Emi_Calculator/Loan_Emi_Calculator/frontend_loan_calendar && npm run build
        env:
          REACT_APP_WELCOME_TEXT: ${{ vars.REACT_APP_WELCOME_TEXT }}
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1  # Verified Marketplace action for GitHub Pages deployment
        with:
          token: ${{ secrets.PAGES_TOKEN }}
          artifact_name: github-pages
          preview: false

   
